### ISSUE TITLE
Error run multiple account.

### ISSUE THREAD

**Issue by zufan-yp** [fakhrirofi/twitter_autobase#11]
How to fix error running multiple account,

File "/root/bot/twitter_autobase/app.py", line 11
    import config2
IndentationError: unexpected indent

![image](https://user-images.githubusercontent.com/78656480/115124395-3417b800-9fec-11eb-900c-7973de01756f.png)

My config, I have made config and config2

![image](https://user-images.githubusercontent.com/78656480/115124435-6c1efb00-9fec-11eb-9f72-1b6babf24ac1.png)

My app.py

![image](https://user-images.githubusercontent.com/78656480/115124485-ad170f80-9fec-11eb-9b75-3c973eb46d37.png)

and

![image](https://user-images.githubusercontent.com/78656480/115124491-b902d180-9fec-11eb-98c1-2d2f55145e54.png)

**Comment by fakhrirofi** [comment]
Based on error code, indent error on line 11. Remove spaces before 'import' on line 11

**Comment by fakhrirofi** [comment]
Check the indentation at lines 29, 31, and 32 as well
