### ISSUE TITLE
bukan issue, pengen nanya aja

### ISSUE THREAD

**Issue by bdrsmsdn** [fakhrirofi/twitter_autobase#2]
kalo pengen nambahin muted word gimana? kaya kalo ada yg dm pake kata muted words, tweetnya ga dikirim

**Comment by fakhrirofi** [comment]
Di constants bikin list baru, misal variabel nya muted_words.
constants.py
`muted_words =  ["word1", "word2", "word-n"] `

Trus di app.py kasih if lagi sebelum line 28.
app.py
`if any(i in message for i in constants.muted_words) == True:
    break`

**Comment by bdrsmsdn** [comment]
oh iya bang, saya punya kasus lagi. Kan di keywordnya kita gunain huruf kecil "menfess" nah si sender malah ngirim "Menfess" alhasil ga dibaca sama bot.
Disini kita gunain lower(): kan bang, tapi gua bingung nyimpennya dimana?

**Comment by fakhrirofi** [comment]
Di app.py aja. 
`If constants.((keyword)) in message.lower()'

**Comment by arepson** [comment]
Untuk menampilkan trigger word di Tweet bagaimana?

**Comment by arepson** [comment]
![image](https://user-images.githubusercontent.com/45273945/102564916-03437700-410f-11eb-8ce5-bf7de2d476b1.png)
Karena ketika menjadi Tweet tidak ada Trigger Word

**Comment by fakhrirofi** [comment]
Di administrator_data. Ubah keyword deleter ke False

**Comment by arepson** [comment]
Terima kasih 🙏

**Comment by arepson** [comment]
Apakah bisa dipasang source label dibawah Tweet?
https://help.twitter.com/id/using-twitter/how-to-tweet#source-labels

**Comment by fakhrirofi** [comment]
Seharusnya setelah bikin akun developer dan pake API nya, source labelnya langsung muncul sendiri. Tapi ngga tau kenapa setelah ada Twitter API v.2 jadi ngga muncul source label-nya.
